export const BADGE_DEFS = [
  { id: "verified", name: "Verified", icon: "BadgeCheck", desc: "Official verified creator identity.", color: "#5B8DB8" },
  { id: "OG", name: "OG Member", icon: "Crown", desc: "One of the original early adopters.", color: "#eab308" },
  { id: "admin", name: "Administrator", icon: "ShieldCheck", desc: "Core administrator & team lead.", color: "#ef4444" },
  { id: "staff", name: "Staff Member", icon: "Wrench", desc: "Official platform team member.", color: "#f97316" },
  { id: "developer", name: "Developer", icon: "Code2", desc: "Core engineer & contributor.", color: "#06b6d4" },
  { id: "donator", name: "Supporter", icon: "HeartHandshake", desc: "Generously supported platform growth.", color: "#ec4899" },
  { id: "early supporter", name: "Early Supporter", icon: "Sparkles", desc: "Believed in the vision from day one.", color: "#8b5cf6" },
  { id: "booster", name: "Server Booster", icon: "Rocket", desc: "Active community Discord server booster.", color: "#a855f7" },
  { id: "creator", name: "Creator", icon: "Clapperboard", desc: "Official content creator & artist.", color: "#10b981" },
  { id: "bug finder", name: "Bug Hunter", icon: "ShieldAlert", desc: "Discovered and reported a security flaw.", color: "#22c55e" },
  { id: "tester", name: "Alpha Tester", icon: "Sparkle", desc: "Beta test pilot and feature tester.", color: "#38bdf8" },
  { id: "vip", name: "VIP", icon: "Award", desc: "Exclusive recognized VIP member.", color: "#f59e0b" },
];

export const BADGE_CATEGORIES = [
  { id: "all", name: "All (100+)" },
  { id: "crowns", name: "Crowns & Trophies" },
  { id: "tactical", name: "Tactical & Weapons" },
  { id: "security", name: "Shields & Security" },
  { id: "tech", name: "Tech & Code" },
  { id: "gaming", name: "Gaming & Media" },
  { id: "cosmic", name: "Cosmic & Magic" },
  { id: "social", name: "Social & Community" },
  { id: "nature", name: "Nature & Elements" },
  { id: "symbols", name: "Symbols & Status" },
];

export const BADGE_ICON_CATALOG = [
  // Crowns, Trophies & Ranks (category: crowns)
  { icon: "Crown", category: "crowns" },
  { icon: "Trophy", category: "crowns" },
  { icon: "Award", category: "crowns" },
  { icon: "Medal", category: "crowns" },
  { icon: "Gem", category: "crowns" },
  { icon: "Diamond", category: "crowns" },
  { icon: "Star", category: "crowns" },
  { icon: "Sparkles", category: "crowns" },
  { icon: "Sparkle", category: "crowns" },
  { icon: "Zap", category: "crowns" },

  // Weapons & Tactical (category: tactical)
  { icon: "Crosshair", category: "tactical" },
  { icon: "Target", category: "tactical" },
  { icon: "Sword", category: "tactical" },
  { icon: "Axe", category: "tactical" },
  { icon: "Bomb", category: "tactical" },
  { icon: "Skull", category: "tactical" },
  { icon: "Ghost", category: "tactical" },
  { icon: "Flame", category: "tactical" },
  { icon: "FlameKindling", category: "tactical" },
  { icon: "ShieldAlert", category: "tactical" },

  // Shields & Security (category: security)
  { icon: "Shield", category: "security" },
  { icon: "ShieldCheck", category: "security" },
  { icon: "ShieldOff", category: "security" },
  { icon: "Lock", category: "security" },
  { icon: "Unlock", category: "security" },
  { icon: "Key", category: "security" },
  { icon: "KeyRound", category: "security" },
  { icon: "Fingerprint", category: "security" },
  { icon: "Eye", category: "security" },
  { icon: "EyeOff", category: "security" },

  // Tech, Dev & Code (category: tech)
  { icon: "Code", category: "tech" },
  { icon: "Code2", category: "tech" },
  { icon: "Terminal", category: "tech" },
  { icon: "Cpu", category: "tech" },
  { icon: "Database", category: "tech" },
  { icon: "Binary", category: "tech" },
  { icon: "Server", category: "tech" },
  { icon: "HardDrive", category: "tech" },
  { icon: "Laptop", category: "tech" },
  { icon: "Wifi", category: "tech" },
  { icon: "Radio", category: "tech" },
  { icon: "Atom", category: "tech" },
  { icon: "Layers", category: "tech" },
  { icon: "Boxes", category: "tech" },

  // Gaming & Entertainment (category: gaming)
  { icon: "Gamepad", category: "gaming" },
  { icon: "Gamepad2", category: "gaming" },
  { icon: "Joystick", category: "gaming" },
  { icon: "Dice5", category: "gaming" },
  { icon: "Disc", category: "gaming" },
  { icon: "Disc3", category: "gaming" },
  { icon: "Headphones", category: "gaming" },
  { icon: "Music", category: "gaming" },
  { icon: "Music2", category: "gaming" },
  { icon: "Music3", category: "gaming" },
  { icon: "Clapperboard", category: "gaming" },
  { icon: "Film", category: "gaming" },
  { icon: "Video", category: "gaming" },
  { icon: "Camera", category: "gaming" },
  { icon: "Tv", category: "gaming" },
  { icon: "RadioTower", category: "gaming" },

  // Cosmic & Astronomy (category: cosmic)
  { icon: "Orbit", category: "cosmic" },
  { icon: "Sun", category: "cosmic" },
  { icon: "Moon", category: "cosmic" },
  { icon: "CloudLightning", category: "cosmic" },
  { icon: "CloudRain", category: "cosmic" },
  { icon: "Feather", category: "cosmic" },
  { icon: "Compass", category: "cosmic" },
  { icon: "Magnet", category: "cosmic" },
  { icon: "Infinity", category: "cosmic" },
  { icon: "Wand2", category: "cosmic" },
  { icon: "Hourglass", category: "cosmic" },
  { icon: "Telescope", category: "cosmic" },

  // Community & Social (category: social)
  { icon: "Heart", category: "social" },
  { icon: "HeartHandshake", category: "social" },
  { icon: "Users", category: "social" },
  { icon: "UserCheck", category: "social" },
  { icon: "UserPlus", category: "social" },
  { icon: "MessageSquare", category: "social" },
  { icon: "Bot", category: "social" },
  { icon: "Rocket", category: "social" },
  { icon: "Megaphone", category: "social" },
  { icon: "Flag", category: "social" },
  { icon: "Send", category: "social" },
  { icon: "Gift", category: "social" },
  { icon: "Smile", category: "social" },

  // Nature & Elements (category: nature)
  { icon: "Leaf", category: "nature" },
  { icon: "Trees", category: "nature" },
  { icon: "Flower2", category: "nature" },
  { icon: "Droplets", category: "nature" },
  { icon: "Waves", category: "nature" },
  { icon: "Wind", category: "nature" },
  { icon: "Mountain", category: "nature" },
  { icon: "Globe", category: "nature" },
  { icon: "Anchor", category: "nature" },
  { icon: "SunDim", category: "nature" },

  // Badges & Symbols (category: symbols)
  { icon: "BadgeCheck", category: "symbols" },
  { icon: "BadgePercent", category: "symbols" },
  { icon: "CheckCircle", category: "symbols" },
  { icon: "HelpCircle", category: "symbols" },
  { icon: "AlertTriangle", category: "symbols" },
  { icon: "Info", category: "symbols" },
  { icon: "Bookmark", category: "symbols" },
  { icon: "Pin", category: "symbols" },
  { icon: "Tags", category: "symbols" },
  { icon: "Bell", category: "symbols" },
  { icon: "Check", category: "symbols" },
  { icon: "ShieldQuestion", category: "symbols" }
];

