import {
  SiDiscord,
  SiSpotify,
  SiX,
  SiInstagram,
  SiGithub,
  SiYoutube,
  SiTwitch,
  SiTelegram,
  SiTiktok,
  SiGoogle,
  SiGmail,
  SiKick,
  SiSnapchat,
  SiReddit,
  SiPinterest,
  SiSoundcloud,
  SiSteam,
  SiPlaystation,
  SiRoblox,
  SiFacebook,
  SiApplemusic,
  SiPatreon,
  SiThreads,
  SiBluesky,
  SiRiotgames,
  SiEpicgames,
  SiBattledotnet,
} from "react-icons/si";
import { FaXbox, FaLinkedin, FaGamepad } from "react-icons/fa6";
import { Globe, ShoppingBag, Mail, Link2, MessageCircle, Music2 } from "lucide-react";

// Real brand marks with sensible fallbacks.
export const BRAND = {
  // Socials & Video
  discord: SiDiscord,
  spotify: SiSpotify,
  twitter: SiX,
  x: SiX,
  instagram: SiInstagram,
  github: SiGithub,
  youtube: SiYoutube,
  twitch: SiTwitch,
  kick: SiKick,
  tiktok: SiTiktok,
  telegram: SiTelegram,
  snapchat: SiSnapchat,
  reddit: SiReddit,
  pinterest: SiPinterest,
  threads: SiThreads,
  bluesky: SiBluesky,
  facebook: SiFacebook,
  linkedin: FaLinkedin,
  patreon: SiPatreon,

  // Music & Audio
  soundcloud: SiSoundcloud,
  applemusic: SiApplemusic,
  apple: SiApplemusic,

  // Gaming
  steam: SiSteam,
  psn: SiPlaystation,
  playstation: SiPlaystation,
  xbox: FaXbox,
  roblox: SiRoblox,
  facepunch: FaGamepad,
  riot: SiRiotgames,
  riotgames: SiRiotgames,
  epic: SiEpicgames,
  epicgames: SiEpicgames,
  battlenet: SiBattledotnet,

  // Utilities & Contact
  google: SiGoogle,
  gmail: SiGmail,
  email: Mail,
  mail: Mail,
  website: Globe,
  shop: ShoppingBag,
  store: ShoppingBag,
  other: Link2,
};

export function brandIcon(platform) {
  const p = (platform || "").toLowerCase().trim().replace(/[^a-z0-9]/g, "");
  return BRAND[p] || BRAND[platform?.toLowerCase()] || Link2;
}

export const BRAND_COLORS = {
  discord: "#5865F2",
  twitter: "#1DA1F2",
  x: "#E5E7EB",
  instagram: "#E4405F",
  github: "#E5E7EB",
  youtube: "#FF0000",
  twitch: "#9146FF",
  kick: "#53FC18",
  tiktok: "#00F2FE",
  telegram: "#26A5E4",
  spotify: "#1DB954",
  snapchat: "#FFFC00",
  reddit: "#FF4500",
  pinterest: "#E60023",
  soundcloud: "#FF5500",
  steam: "#66C0F4",
  psn: "#0070D1",
  playstation: "#0070D1",
  xbox: "#107C10",
  roblox: "#E5E7EB",
  linkedin: "#0A66C2",
  facebook: "#1877F2",
  applemusic: "#FA2D48",
  apple: "#FA2D48",
  patreon: "#FF424D",
  threads: "#E5E7EB",
  bluesky: "#0285FF",
  facepunch: "#EA580C",
  riot: "#D32936",
  riotgames: "#D32936",
  epic: "#313131",
  epicgames: "#313131",
  battlenet: "#00AEFF",
  google: "#EA4335",
  gmail: "#EA4335",
  website: "#5B8DB8",
  shop: "#F59E0B",
  other: "#5B8DB8",
};

